name: Run CI and potentially release
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  nodejs-lib-ci:
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-lib-ci.yml@main

  release:
    needs: nodejs-lib-ci
    uses: relaycorp/shared-workflows/.github/workflows/nodejs-lib-release.yml@main
    with:
      jekyll_docs: true
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}

  ci:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
